# Generated by Django 3.1.4 on 2020-12-07 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.IntegerField(primary_key=True, serialize=False)),
                ('register_id', models.DateTimeField()),
                ('first_name', models.TextField(max_length=255)),
                ('last_name', models.TextField(max_length=255)),
                ('age', models.IntegerField()),
                ('mobile', models.TextField(max_length=255)),
                ('phone', models.TextField(max_length=255)),
                ('address', models.TextField(max_length=255)),
            ],
        ),
    ]
