# Generated by Django 3.1.4 on 2020-12-07 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.TextField(max_length=50, null=True),
        ),
    ]
